# Configuration for state classification model

# General settings
seed: 42
batch_size: 256
num_workers: 8
train_val_split: 0.9
full_dataset_size: 1.0
prefetch_factor: 4

# Paths (these are overridden in Colab)
dataset_root: "data/train"
test_dataset_root: "data/test"
checkpoints_dir: "checkpoints"
test_groups_per_batch: 16

# Model configuration
model_cfg:
  num_classes: 50
  architecture: "resnet101"
  pretrained: true

# Training hyperparameters
hyperparameters:
  # Phase 1: Head-only training
  weight_decay: 0.01
  momentum: 0.9
  betas: [0.9, 0.999]
  optimizer: "Adam"

  phase1_epochs: 10
  phase1_lr: 0.001


  # Phase 2: Fine-tuning
  phase2_epochs: 5
  phase2_lr: 0.0005

  phase3_epochs: 3
  phase3_lr: 0.00025

  # Early stopping
  patience: 3
  early_stopping_delta: 0.001

train_phases:
  start_phase: 1
  phase1: True
  phase2: True
  phase3: True
# Wandb settings
wandb:
  project: "state-classifier"
  log_interval: 10